"""Email dispatch service supporting simulated mock dispatch and optional real SMTP."""

import os
import smtplib
import logging
import datetime
from email.message import EmailMessage
from pathlib import Path
from typing import Optional

from app.config import (
    HR_EMAIL,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USERNAME,
    SMTP_PASSWORD,
    GENERATED_DIR,
)
from app.models import DispatchResponse

logger = logging.getLogger(__name__)


def dispatch_evaluation(
    file_path: Optional[str] = None,
    recipient: Optional[str] = None,
) -> DispatchResponse:
    """
    Dispatch the generated evaluation document to HR.
    By default operates in 'simulated' mock mode unless real SMTP credentials are provided.
    """
    target_recipient = (recipient or HR_EMAIL or "hr-admissions@company.mock").strip()
    
    # Resolve file path
    if file_path:
        path = Path(file_path)
        if not path.is_absolute():
            path = GENERATED_DIR / file_path
    else:
        # Pick the most recently generated evaluation if none specified
        pdf_files = sorted(GENERATED_DIR.glob("*.pdf"), key=os.path.getmtime, reverse=True)
        if not pdf_files:
            raise FileNotFoundError("No generated evaluation file found to dispatch.")
        path = pdf_files[0]

    if not path.exists():
        raise FileNotFoundError(f"Evaluation file not found at path: {path}")

    attachment_name = path.name
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Optional real SMTP dispatch if configured
    if SMTP_HOST and SMTP_USERNAME and SMTP_PASSWORD:
        try:
            msg = EmailMessage()
            msg["Subject"] = f"Candidate Evaluation Dispatch: {attachment_name}"
            msg["From"] = SMTP_USERNAME
            msg["To"] = target_recipient
            msg.set_content(
                f"Attached is the candidate evaluation report generated by AI Recruiter Agent at {now_str}."
            )

            with open(path, "rb") as f:
                file_data = f.read()
            msg.add_attachment(file_data, maintype="application", subtype="pdf", filename=attachment_name)

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USERNAME, SMTP_PASSWORD)
                server.send_message(msg)

            logger.info(f"Evaluation email successfully sent via SMTP to {target_recipient}")
            return DispatchResponse(
                status="sent",
                recipient=target_recipient,
                attachment=attachment_name,
                timestamp=now_str,
                message=f"Evaluation successfully emailed to {target_recipient} via SMTP server.",
            )
        except Exception as exc:
            logger.warning(f"SMTP dispatch failed ({exc}), falling back to simulated dispatch.")

    # Default Mock / Simulated Dispatch
    logger.info(f"Mock email dispatch completed for {target_recipient} with attachment {attachment_name}")
    return DispatchResponse(
        status="simulated",
        recipient=target_recipient,
        attachment=attachment_name,
        timestamp=now_str,
        message=f"Simulated email dispatch to {target_recipient} with attachment '{attachment_name}' succeeded.",
    )
